[package]
name = "armstrong"
version = "0.1.0"
authors = ["FeÌlix Saparelli <felix@passcod.name>"]
license = "Artistic-2.0"
repository = "https://github.com/passcod/armstrong"
# readme = "README.md"

edition = "2018"

[badges]
travis-ci = { repository = "passcod/armstrong" }
maintenance = { status = "actively-developed" }

[dependencies]
hostname = "0.1.5"
ipnet = "2.0.0"
lazy_static = "1.2.0"
log = "0.4.6"
num_cpus = "1.9.0"
ocl-core = "0.10.0"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.34"
systemstat = "0.1.3"
url = "1.7.2"
ws = "0.7.9"

[dependencies.uuid]
version = "0.7.1"
features = ["serde", "u128"]
